In [19]:
import numpy as np
import pandas as pd

X=pd.read_csv("../Data/original/cleaned_X.csv")
y=pd.read_csv("../Data/original/cleaned_y.csv")

y=y["Label_dark"]
y

0         0
1         0
2         0
3         0
4         0
         ..
117019    1
117020    1
117021    1
117022    1
117023    1
Name: Label_dark, Length: 117024, dtype: int64

# Perform random undersampling

In [7]:
from imblearn.under_sampling import RandomUnderSampler

under=RandomUnderSampler()

X_und,y_und=under.fit_resample(X,y)

print(len(X_und[X_und==1])==len(X_und[X_und==0]))

     |████████████████████████████████| 199 kB 1.9 MB/s            
     |████████████████████████████████| 26.7 MB 9.9 MB/s            
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.23.2
    Uninstalling scikit-learn-0.23.2:
      Successfully uninstalled scikit-learn-0.23.2
You should consider upgrading via the '/home/drake/miniconda3/bin/python -m pip install --upgrade pip' command.
True


In [19]:
X_und.to_csv("../Data/synthetic/RandomUndersampling/using_darknet_labelX.csv")
y_und.to_csv("../Data/synthetic/RandomUndersampling/using_darknet_labely.csv")

# Perforn random oversampling

In [10]:
from imblearn.over_sampling import RandomOverSampler

over=RandomOverSampler()

X_over,y_over=over.fit_resample(X,y)

In [22]:
X_over.to_csv("../Data/synthetic/RandomOversampling/using_darknet_labelX.csv")
y_over.to_csv("../Data/synthetic/RandomOversampling/using_darknet_labely.csv")

# Direct undersampling
### Using Edited Nearest Neighbors, Instance Hardness Threshold, and TomekLinks

In [24]:
from imblearn.under_sampling import EditedNearestNeighbours,InstanceHardnessThreshold,TomekLinks 

under_samp_models=[EditedNearestNeighbours(),InstanceHardnessThreshold(),TomekLinks()]
under_samp_names=["EditedNearestNeighbours","InstanceHardnessThreshold", "TomekLinks"]

for i,under_samp_model in enumerate(under_samp_models):
    X_und_dir,y_und_dir=under_samp_model.fit_resample(X,y)
    X_und_dir.to_csv(f"../Data/synthetic/DirectedUndersampling/{under_samp_names[i]}X.csv")
    y_und_dir.to_csv(f"../Data/synthetic/DirectedUndersampling/{under_samp_names[i]}y.csv")

# Directed Oversampling Using Smote 

In [6]:
import smote_variants as sv 

svs=[sv.kmeans_SMOTE(),sv.Safe_Level_SMOTE(),sv.SMOTE_Cosine()]

for over_sampler in svs: 
    X_over_samp, y_over_samp = over_sampler.sample(X, y)
    print(X_over_samp)

2022-02-11 12:35:26,711:INFO:kmeans_SMOTE: Running sampling via ('kmeans_SMOTE', "{'proportion': 1.0, 'n_neighbors': 5, 'n_clusters': 10, 'irt': 2.0, 'n_jobs': 1, 'random_state': None}")
2022-02-11 12:35:27,768:WARNING:kmeans_SMOTE: number of clusters after filtering is 0
2022-02-11 12:35:27,803:INFO:Safe_Level_SMOTE: Running sampling via ('Safe_Level_SMOTE', "{'proportion': 1.0, 'n_neighbors': 5, 'n_jobs': 1, 'random_state': None}")


        Src Port  Dst Port  Protocol  Flow Duration  Total Fwd Packet  \
0          57158       443         6            229                 1   
1          57159       443         6            407                 1   
2          57160       443         6            431                 1   
3          49134       443         6            359                 1   
4          34697     19305         6       10778451               591   
...          ...       ...       ...            ...               ...   
117019     55219      5355        17         411806                 2   
117020     64207      5355        17         411574                 2   
117021     61115      5355        17         422299                 2   
117022     64790      5355        17         411855                 2   
117023     11666     60245        17      119990044              5995   

        Total Bwd packets  Total Length of Fwd Packet  \
0                       1                           0   
1        

KeyboardInterrupt: 

# Over 85 SMOTE Variants

In [2]:
import smote_variants as sv 

variants = [sv.kmeans_SMOTE(), sv.SMOTE(), sv.SMOTE_TomekLinks(), sv.SMOTE_ENN(), sv.Borderline_SMOTE1(), sv.Borderline_SMOTE2(), sv.ADASYN(), sv.AHC(), sv.LLE_SMOTE(), sv.distance_SMOTE(), sv.SMMO(), sv.polynom_fit_SMOTE(), sv.Stefanowski(), sv.ADOMS(), sv.Safe_Level_SMOTE(), sv.MSMOTE(), sv.DE_oversampling(), sv.SMOBD(), sv.SUNDO(), sv.MSYN(), sv.SVM_balance(), sv.TRIM_SMOTE(), sv.SMOTE_RSB(), sv.ProWSyn(), sv.SL_graph_SMOTE(), sv.NRSBoundary_SMOTE(), sv.LVQ_SMOTE(), sv.SOI_CJ(), sv.ROSE(), sv.SMOTE_OUT(), sv.SMOTE_Cosine(), sv.Selected_SMOTE(), sv.LN_SMOTE(), sv.MWMOTE(), sv.PDFOS(), sv.IPADE_ID(), sv.RWO_sampling(), sv.NEATER(), sv.DEAGO(), sv.Gazzah(), sv.MCT(), sv.ADG(), sv.SMOTE_IPF(), sv.KernelADASYN(), sv.MOT2LD(), sv.V_SYNTH(), sv.OUPS(), sv.SMOTE_D(), sv.SMOTE_PSO(), sv.CURE_SMOTE(), sv.SOMO(), sv.ISOMAP_Hybrid(), sv.CE_SMOTE(), sv.Edge_Det_SMOTE(), sv.CBSO(), sv.E_SMOTE(), sv.DBSMOTE(), sv.ASMOBD(), sv.Assembled_SMOTE(), sv.SDSMOTE(), sv.DSMOTE(), sv.G_SMOTE(), sv.NT_SMOTE(), sv.Lee(), sv.SPY(), sv.SMOTE_PSOBAT(), sv.MDO(), sv.Random_SMOTE(), sv.ISMOTE(), sv.VIS_RST(), sv.GASMOTE(), sv.A_SUWO(), sv.SMOTE_FRST_2T(), sv.AND_SMOTE(), sv.NRAS(), sv.AMSCO(), sv.SSO(), sv.NDO_sampling(), sv.DSRBF(), sv.Gaussian_SMOTE(), sv.kmeans_SMOTE(), sv.Supervised_SMOTE(), sv.SN_SMOTE(), sv.CCR(), sv.ANS(), sv.cluster_SMOTE(), sv.NoSMOTE()]

In [ ]:
succesful = []
failed = []
progress = 0

for variant in variants:
    oversampler= variant
    try:
        X_over_samp, y_over_samp = oversampler.sample(X, y)
        succesful.append(oversampler)
    except:
        failed.append(oversampler)
    progress += 1
    if progress % 5 == 0:
        print(f"{progress} samples out of {len(variants)} completed. {len(succesful)} passed and {len(failed)} failed")

2022-02-11 12:07:56,666:INFO:kmeans_SMOTE: Running sampling via ('kmeans_SMOTE', "{'proportion': 1.0, 'n_neighbors': 5, 'n_clusters': 10, 'irt': 2.0, 'n_jobs': 1, 'random_state': None}")
2022-02-11 12:07:57,706:WARNING:kmeans_SMOTE: number of clusters after filtering is 0
2022-02-11 12:07:57,719:INFO:SMOTE: Running sampling via ('SMOTE', "{'proportion': 1.0, 'n_neighbors': 5, 'n_jobs': 1, 'random_state': None}")
2022-02-11 12:08:03,889:INFO:SMOTE_TomekLinks: Running sampling via ('SMOTE_TomekLinks', "{'proportion': 1.0, 'n_neighbors': 5, 'n_jobs': 1, 'random_state': None}")
2022-02-11 12:08:03,889:INFO:SMOTE: Running sampling via ('SMOTE', "{'proportion': 1.0, 'n_neighbors': 5, 'n_jobs': 1, 'random_state': <module 'numpy.random' from '/home/drake/miniconda3/lib/python3.8/site-packages/numpy/random/__init__.py'>}")
2022-02-11 12:08:10,027:INFO:SMOTE_ENN: Running sampling via ('SMOTE_ENN', "{'proportion': 1.0, 'n_neighbors': 5, 'n_jobs': 1, 'random_state': None}")
2022-02-11 12:08:10,028

5 samples out of 87 completed. 1 passed and 4 failed


2022-02-11 12:09:54,966:INFO:ADASYN: Running sampling via ('ADASYN', "{'n_neighbors': 5, 'd_th': 0.9, 'beta': 1.0, 'n_jobs': 1, 'random_state': None}")
2022-02-11 12:10:45,812:INFO:AHC: Running sampling via ('AHC', "{'strategy': 'min', 'n_jobs': 1, 'random_state': None}")
2022-02-11 12:11:12,085:INFO:LLE_SMOTE: Running sampling via ('LLE_SMOTE', "{'proportion': 1.0, 'n_neighbors': 5, 'n_components': 2, 'n_jobs': 1, 'random_state': None}")
2022-02-11 12:11:12,092:INFO:distance_SMOTE: Running sampling via ('distance_SMOTE', "{'proportion': 1.0, 'n_neighbors': 5, 'n_jobs': 1, 'random_state': None}")
2022-02-11 12:11:18,365:INFO:SMMO: Running sampling via ('SMMO', "{'proportion': 1.0, 'n_neighbors': 5, 'ensemble': [QuadraticDiscriminantAnalysis(), DecisionTreeClassifier(random_state=2), GaussianNB()], 'n_jobs': 1, 'random_state': None}")


10 samples out of 87 completed. 1 passed and 9 failed


2022-02-11 12:11:21,965:INFO:polynom_fit_SMOTE: Running sampling via ('polynom_fit_SMOTE', "{'proportion': 1.0, 'topology': 'star', 'random_state': None}")
2022-02-11 12:11:21,972:INFO:Stefanowski: Running sampling via ('Stefanowski', "{'strategy': 'weak_amp', 'n_jobs': 1}")
2022-02-11 12:18:06,177:INFO:ADOMS: Running sampling via ('ADOMS', "{'proportion': 1.0, 'n_neighbors': 5, 'n_jobs': 1, 'random_state': None}")
2022-02-11 12:18:12,196:INFO:Safe_Level_SMOTE: Running sampling via ('Safe_Level_SMOTE', "{'proportion': 1.0, 'n_neighbors': 5, 'n_jobs': 1, 'random_state': None}")
2022-02-11 12:21:18,204:INFO:MSMOTE: Running sampling via ('MSMOTE', "{'proportion': 1.0, 'n_neighbors': 5, 'n_jobs': 1, 'random_state': None}")


15 samples out of 87 completed. 1 passed and 14 failed


2022-02-11 12:21:54,457:INFO:DE_oversampling: Running sampling via ('DE_oversampling', "{'proportion': 1.0, 'n_neighbors': 5, 'crossover_rate': 0.5, 'similarity_threshold': 0.5, 'n_clusters': 30, 'n_jobs': 1, 'random_state': None}")
2022-02-11 12:21:54,459:INFO:SMOBD: Running sampling via ('SMOBD', "{'proportion': 1.0, 'eta1': 0.5, 't': 1.8, 'min_samples': 5, 'max_eps': 1.0, 'n_jobs': 1, 'random_state': None}")
2022-02-11 12:22:08,246:INFO:SUNDO: Running sampling via ('SUNDO', "{'n_jobs': 1, 'random_state': None}")
2022-02-11 12:22:08,283:INFO:MSYN: Running sampling via ('MSYN', "{'pressure': 1.5, 'n_neighbors': 5, 'n_jobs': 1, 'random_state': None}")
2022-02-11 12:22:08,297:INFO:SMOTE: Running sampling via ('SMOTE', "{'proportion': 1.5, 'n_neighbors': 5, 'n_jobs': 1, 'random_state': <module 'numpy.random' from '/home/drake/miniconda3/lib/python3.8/site-packages/numpy/random/__init__.py'>}")
2022-02-11 12:22:15,058:INFO:SVM_balance: Running sampling via ('SVM_balance', "{'proportion': 

20 samples out of 87 completed. 1 passed and 19 failed


2022-02-11 12:22:21,764:INFO:TRIM_SMOTE: Running sampling via ('TRIM_SMOTE', "{'proportion': 1.0, 'n_neighbors': 5, 'min_precision': 0.3, 'n_jobs': 1, 'random_state': None}")
2022-02-11 12:22:21,766:INFO:TRIM_SMOTE: do the trimming process
2022-02-11 12:22:21,767:INFO:SMOTE_RSB: Running sampling via ('SMOTE_RSB', "{'proportion': 2.0, 'n_neighbors': 5, 'n_jobs': 1, 'random_state': None}")
2022-02-11 12:22:21,785:INFO:SMOTE: Running sampling via ('SMOTE', "{'proportion': 2.0, 'n_neighbors': 5, 'n_jobs': 1, 'random_state': <module 'numpy.random' from '/home/drake/miniconda3/lib/python3.8/site-packages/numpy/random/__init__.py'>}")
2022-02-11 12:22:28,733:INFO:ProWSyn: Running sampling via ('ProWSyn', "{'proportion': 1.0, 'n_neighbors': 5, 'L': 5, 'theta': 1.0, 'n_jobs': 1, 'random_state': None}")
2022-02-11 12:22:28,751:INFO:SL_graph_SMOTE: Running sampling via ('SL_graph_SMOTE', "{'proportion': 1.0, 'n_neighbors': 5, 'n_jobs': 1, 'random_state': None}")
2022-02-11 12:23:20,567:INFO:Safe_

25 samples out of 87 completed. 1 passed and 24 failed


/home/drake/miniconda3/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(
2022-02-11 12:26:46,805:INFO:SOI_CJ: Running sampling via ('SOI_CJ', "{'proportion': 1.0, 'n_neighbors': 5, 'method': 'interpolation', 'n_jobs': 1, 'random_state': None}")
2022-02-11 12:26:46,820:INFO:SOI_CJ: Executing clustering


In [20]:
X = X.to_numpy()
y = y.to_numpy()

array([0, 0, 0, ..., 1, 1, 1])

In [21]:
sv.Safe_Level_SMOTE().sample(X, y)

2022-02-11 12:40:56,668:INFO:Safe_Level_SMOTE: Running sampling via ('Safe_Level_SMOTE', "{'proportion': 1.0, 'n_neighbors': 5, 'n_jobs': 1, 'random_state': None}")


(array([[5.71580000e+04, 4.43000000e+02, 6.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [5.71590000e+04, 4.43000000e+02, 6.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [5.71600000e+04, 4.43000000e+02, 6.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        ...,
        [5.09137492e+04, 1.72347338e+02, 6.00000000e+00, ...,
         2.24687209e+07, 1.46000000e+15, 1.45634000e+15],
        [4.06690000e+04, 8.00000000e+01, 6.00000000e+00, ...,
         3.68745430e+07, 1.45634000e+15, 1.45634000e+15],
        [3.67195880e+04, 4.43000000e+02, 6.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00]]),
 array([0, 0, 0, ..., 1, 1, 1]))

# Their example

In [14]:
import smote_variants as sv
import imbalanced_databases as imbd

dataset= imbd.load_iris0()
X, y= dataset['data'], dataset['target']

X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3